# This is a YAML-formatted file.
# Declare variables to be passed into your templates.]
version: 1.0
replicaCount: 1
revisionHistoryLimit: 4
containerPort: 8080
imageConfig:
  pullPolicy: Always
  image: rapidolabs/silent-assassin:1.0.4-0b57d81a

resources:
  enabled: true
  requests:
    cpu: 20m
    memory: 20Mi
  limits:
    cpu: 100m
    memory: 100Mi

daemonset:
  resources:
    enabled: true
    requests:
      cpu: 10m
      memory: 10Mi
    limits:
      cpu: 20m
      memory: 20Mi

affinity: {}

service:
  type: ClusterIP
  servicePort: 80

# when using workload identity set this to the Google Cloud Service Account
workloadIdentityServiceAccount:
  enabled: true
  email: ""

secret:
  # if set to true the values are already base64 encoded when provided, otherwise the template performs the base64 encoding
  # this value will be ignored if workloadIdentityServiceAccount is enabled.
  valuesAreBase64Encoded: false

  # sets a json keyfile for a gcp service account. Add contnent of json key file with no new lines.
  # this value will be ignored if workloadIdentityServiceAccount is enabled.
  googleServiceAccountKeyfileJson: '{"type": "service_account","project_id":".."}'

silent_assassin:
  node_selectors: "cloud.google.com/gke-preemptible=true"
  # debug | info | warn | error
  logger_level: "info"
  # InCluster | OutCluster
  k8s_run_mode: InCluster
  spotter:
    poll_interval: 1s
    white_list_interval_hours: "06:30-08:30,18:30-00:30"
  killer:
    poll_interval: 1s
    draining_timeout_when_node_expired: 5m
    draining_timeout_when_node_preempted: 25s
    evict_delete_deadline: 30s
    grace_period_seconds_when_pod_deleted: 20

  shifter:
    enabled: true
    poll_interval: 20m
    white_list_interval_hours: 19:30-21:30
    np_resize_timeout: 10m
    sleep_after_node_deletion: 120s
  slack:
    webhook_url: ""
    username: "SILENT-ASSASSIN"
    channel: ""
    icon_url: ""
  client:
    server_retries: 4
    watch_maintainance_event: true