{{- if not .Values.workloadIdentityServiceAccount.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ .Chart.Name }}
type: Opaque
{{- if not .Values.secret.useGcpServiceAccountAnnotation }}
data:
  {{- if .Values.secret.valuesAreBase64Encoded }}
  service-account-key.json: {{.Values.secret.googleServiceAccountKeyfileJson | toString}}
  {{- else }}
  service-account-key.json: {{.Values.secret.googleServiceAccountKeyfileJson | toString | b64enc}}
  {{- end }}
{{- end }}
{{- end }}